[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
    colorscheme gruvbox
    set background=dark
    set t_Co=256
    let g:ligthline = { 'colorscheme': 'gruvbox' }
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'wesQ3/vim-windowswap'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'yuku-t/vim-ref-ri'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'thinca/vim-visualstar'

[[plugins]]
repo = 'vim-scripts/DrawIt'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]] # Set the buffer filetype based on the code block the cursor currently resides in
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # Find fenced code blocks and their filetype
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'rhysd/clever-f.vim'
