[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'wesQ3/vim-windowswap'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'
